spring.application.name=project

spring.datasource.url=jdbc:mysql://localhost:3307/db_komplidacademy
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false